#!/bin/bash

# insertar informacion dentro de un archivo
# autor: programador negro

# EOM: End Of Message
# EOF: End Of File

echo "ESCRIBIR EN UN ARCHIVO"

echo "Valores escritos con el comando echo" >> $1

#adicion multilinea

cat << EOM >> $1
$2
EOM